// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBC0UKAIqmlop-PYSw4RM4E1rk9_a8YXSE',
    appId: '1:803611908381:web:ec5e7b71b39d60250169f4',
    messagingSenderId: '803611908381',
    projectId: 'remotesurveyapp',
    authDomain: 'remotesurveyapp.firebaseapp.com',
    storageBucket: 'remotesurveyapp.appspot.com',
    measurementId: 'G-S5N1JYHZDG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRa4MeyI2cjyn4dzT_G--3HFHdFOp6a4s',
    appId: '1:803611908381:android:d1f0a3ee668b68d20169f4',
    messagingSenderId: '803611908381',
    projectId: 'remotesurveyapp',
    storageBucket: 'remotesurveyapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEaw4gLAMFnFJgd_aXqKAqCyTt1MnfeRY',
    appId: '1:803611908381:ios:2773269883ae19890169f4',
    messagingSenderId: '803611908381',
    projectId: 'remotesurveyapp',
    storageBucket: 'remotesurveyapp.appspot.com',
    iosClientId: '803611908381-ip5eiqo1rsq2taaqibecu6en00vcljfa.apps.googleusercontent.com',
    iosBundleId: 'com.example.remotesurveyadmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEaw4gLAMFnFJgd_aXqKAqCyTt1MnfeRY',
    appId: '1:803611908381:ios:2773269883ae19890169f4',
    messagingSenderId: '803611908381',
    projectId: 'remotesurveyapp',
    storageBucket: 'remotesurveyapp.appspot.com',
    iosClientId: '803611908381-ip5eiqo1rsq2taaqibecu6en00vcljfa.apps.googleusercontent.com',
    iosBundleId: 'com.example.remotesurveyadmin',
  );
}
